services:
  db:
    image: postgres:16-alpine
    container_name: taskflow_db
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
      POSTGRES_DB: taskflow
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: taskflow_redis
    ports:
      - '6379:6379'

volumes:
  pgdata: